### ISSUE TITLE
Crash when canceling upload profile photo

### ISSUE THREAD

**Issue by NemanjaIvkovic** [ninoprek/Jumanji-#94]
When entered in profile photo in the create user activity, if user chooses to pick a photo from the library and then presses back button before choosing the picture, error in the log (listed below) will appear and after the second press on the button app will crash.

```05-07 15:51:12.692 1987-1987/jumanji.sda.com.jumanji E/AndroidRuntime: FATAL EXCEPTION: main
    Process: jumanji.sda.com.jumanji, PID: 1987
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=200, result=0, data=null} to activity {jumanji.sda.com.jumanji/jumanji.sda.com.jumanji.CreateProfileActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4520)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4563)
        at android.app.ActivityThread.-wrap22(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
     Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
        at jumanji.sda.com.jumanji.CreateProfileActivity.onActivityResult(CreateProfileActivity.kt)
        at android.app.Activity.dispatchActivityResult(Activity.java:7292)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4516)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4563) 
        at android.app.ActivityThread.-wrap22(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6776) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)```



**Severity:**
High

**Comment by djadifuntorum** [comment]
Fix with this commit
https://github.com/ninoprek/Jumanji-/commit/f87bcc0725faf07e0e51d82af3ccc96bd2e7bd6a

**Comment by djadifuntorum** [comment]
1. Open Camera
2. Select a photo/take a picture
3. Press back button.

**Comment by aaronsum1102** [comment]
Fix refer 5f8107e470b70d5716a88f3f3e98f02e06479c97.

- [ ] to verify

**Comment by djadifuntorum** [comment]
Verified on emulator with commit https://github.com/ninoprek/Jumanji-/commit/a10936f67011146669ac6ce44f44c8cbc55d674c
. Works well already. Need to test on actual phone before closing this issue.

**Comment by djadifuntorum** [comment]
Verified on actual phone also with commit a10936f
. Works well already.
