### ISSUE TITLE
Community tab crashes without location turned on

### ISSUE THREAD

**Issue by NemanjaIvkovic** [ninoprek/Jumanji-#95]
If the location is turned off app crashes when community tab in the home page is pressed.

```
05-07 16:10:06.434 13526-13526/jumanji.sda.com.jumanji E/AndroidRuntime: FATAL EXCEPTION: main
    Process: jumanji.sda.com.jumanji, PID: 13526
    java.lang.IllegalStateException: it must not be null
        at jumanji.sda.com.jumanji.LocationViewModel$moveToLastKnowLocation$1.onSuccess(LocationViewModel.kt:42)
        at jumanji.sda.com.jumanji.LocationViewModel$moveToLastKnowLocation$1.onSuccess(LocationViewModel.kt:19)
        at com.google.android.gms.tasks.zzn.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

**Comment by aaronsum1102** [comment]
Fix for verification. Refer to commit 55c74abd0205f3207cc50e2fb1d11715d012269b
